 import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import  SupabaseStore from './context/SupabaseProvider'
 
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dim">
      <body className={inter.className}><SupabaseStore><Navbar/>{children} </SupabaseStore> </body>
    </html>
  )
}
